-- lazy.nvim
return {
    {
        "robitx/gp.nvim",
        config = function()
            local conf = {
                providers = {
                    openai = {
                        endpoint = "https://api.openai.com/v1/chat/completions",
                        secret = os.getenv("OPENAI_API_KEY"),
                    },

                    anthropic = {
                        endpoint = "https://api.anthropic.com/v1/messages",
                        secret = os.getenv("ANTHROPIC_API_KEY"),
                    },
                },
            }
            require("gp").setup(conf)
            require("which-key").add({
                -- VISUAL mode mappings
                -- s, x, v modes are handled the same way by which_key
                {
                    mode = { "v" },
                    nowait = true,
                    remap = false,
                    { "<leader>gt",  ":<C-u>'<,'>GpChatNew tabnew<cr>", desc = "ChatNew tabnew" },
                    { "<leader>gv",  ":<C-u>'<,'>GpChatNew vsplit<cr>", desc = "ChatNew vsplit" },
                    { "<leader>gx",  ":<C-u>'<,'>GpChatNew split<cr>",  desc = "ChatNew split" },
                    { "<leader>ga",  ":<C-u>'<,'>GpAppend<cr>",         desc = "Visual Append (after)" },
                    { "<leader>gb",  ":<C-u>'<,'>GpPrepend<cr>",        desc = "Visual Prepend (before)" },
                    { "<leader>gc",  ":<C-u>'<,'>GpChatNew<cr>",        desc = "Visual Chat New" },
                    { "<leader>gg",  group = "generate into new .." },
                    { "<leader>gge", ":<C-u>'<,'>GpEnew<cr>",           desc = "Visual GpEnew" },
                    { "<leader>ggn", ":<C-u>'<,'>GpNew<cr>",            desc = "Visual GpNew" },
                    { "<leader>ggp", ":<C-u>'<,'>GpPopup<cr>",          desc = "Visual Popup" },
                    { "<leader>ggt", ":<C-u>'<,'>GpTabnew<cr>",         desc = "Visual GpTabnew" },
                    { "<leader>ggv", ":<C-u>'<,'>GpVnew<cr>",           desc = "Visual GpVnew" },
                    { "<leader>gi",  ":<C-u>'<,'>GpImplement<cr>",      desc = "Implement selection" },
                    { "<leader>gn",  "<cmd>GpNextAgent<cr>",            desc = "Next Agent" },
                    { "<leader>gp",  ":<C-u>'<,'>GpChatPaste<cr>",      desc = "Visual Chat Paste" },
                    { "<leader>gr",  ":<C-u>'<,'>GpRewrite<cr>",        desc = "Visual Rewrite" },
                    { "<leader>gs",  "<cmd>GpStop<cr>",                 desc = "GpStop" },
                    { "<leader>gt",  ":<C-u>'<,'>GpChatToggle<cr>",     desc = "Visual Toggle Chat" },
                    { "<leader>gw",  group = "Whisper" },
                    { "<leader>gwa", ":<C-u>'<,'>GpWhisperAppend<cr>",  desc = "Whisper Append" },
                    { "<leader>gwb", ":<C-u>'<,'>GpWhisperPrepend<cr>", desc = "Whisper Prepend" },
                    { "<leader>gwe", ":<C-u>'<,'>GpWhisperEnew<cr>",    desc = "Whisper Enew" },
                    { "<leader>gwn", ":<C-u>'<,'>GpWhisperNew<cr>",     desc = "Whisper New" },
                    { "<leader>gwp", ":<C-u>'<,'>GpWhisperPopup<cr>",   desc = "Whisper Popup" },
                    { "<leader>gwr", ":<C-u>'<,'>GpWhisperRewrite<cr>", desc = "Whisper Rewrite" },
                    { "<leader>gwt", ":<C-u>'<,'>GpWhisperTabnew<cr>",  desc = "Whisper Tabnew" },
                    { "<leader>gwv", ":<C-u>'<,'>GpWhisperVnew<cr>",    desc = "Whisper Vnew" },
                    { "<leader>gww", ":<C-u>'<,'>GpWhisper<cr>",        desc = "Whisper" },
                    { "<leader>gx",  ":<C-u>'<,'>GpContext<cr>",        desc = "Visual GpContext" },
                },

                -- NORMAL mode mappings
                {
                    mode = { "n" },
                    nowait = true,
                    remap = false,
                    { "<leader>gt", "<cmd>GpChatNew tabnew<cr>",   desc = "New Chat tabnew" },
                    { "<leader>gv", "<cmd>GpChatNew vsplit<cr>",   desc = "New Chat vsplit" },
                    { "<leader>gx", "<cmd>GpChatNew split<cr>",    desc = "New Chat split" },
                    { "<leader>ga",     "<cmd>GpAppend<cr>",           desc = "Append (after)" },
                    { "<leader>gb",     "<cmd>GpPrepend<cr>",          desc = "Prepend (before)" },
                    { "<leader>gc",     "<cmd>GpChatNew<cr>",          desc = "New Chat" },
                    { "<leader>gf",     "<cmd>GpChatFinder<cr>",       desc = "Chat Finder" },
                    { "<leader>gg",     group = "generate into new .." },
                    { "<leader>gge",    "<cmd>GpEnew<cr>",             desc = "GpEnew" },
                    { "<leader>ggn",    "<cmd>GpNew<cr>",              desc = "GpNew" },
                    { "<leader>ggp",    "<cmd>GpPopup<cr>",            desc = "Popup" },
                    { "<leader>ggt",    "<cmd>GpTabnew<cr>",           desc = "GpTabnew" },
                    { "<leader>ggv",    "<cmd>GpVnew<cr>",             desc = "GpVnew" },
                    { "<leader>gn",     "<cmd>GpNextAgent<cr>",        desc = "Next Agent" },
                    { "<leader>gr",     "<cmd>GpRewrite<cr>",          desc = "Inline Rewrite" },
                    { "<leader>gs",     "<cmd>GpStop<cr>",             desc = "GpStop" },
                    { "<leader>gt",     "<cmd>GpChatToggle<cr>",       desc = "Toggle Chat" },
                    { "<leader>gw",     group = "Whisper" },
                    { "<leader>gwa",    "<cmd>GpWhisperAppend<cr>",    desc = "Whisper Append (after)" },
                    { "<leader>gwb",    "<cmd>GpWhisperPrepend<cr>",   desc = "Whisper Prepend (before)" },
                    { "<leader>gwe",    "<cmd>GpWhisperEnew<cr>",      desc = "Whisper Enew" },
                    { "<leader>gwn",    "<cmd>GpWhisperNew<cr>",       desc = "Whisper New" },
                    { "<leader>gwp",    "<cmd>GpWhisperPopup<cr>",     desc = "Whisper Popup" },
                    { "<leader>gwr",    "<cmd>GpWhisperRewrite<cr>",   desc = "Whisper Inline Rewrite" },
                    { "<leader>gwt",    "<cmd>GpWhisperTabnew<cr>",    desc = "Whisper Tabnew" },
                    { "<leader>gwv",    "<cmd>GpWhisperVnew<cr>",      desc = "Whisper Vnew" },
                    { "<leader>gww",    "<cmd>GpWhisper<cr>",          desc = "Whisper" },
                    { "<leader>gx",     "<cmd>GpContext<cr>",          desc = "Toggle GpContext" },
                },

                -- INSERT mode mappings
                {
                    mode = { "i" },
                    nowait = true,
                    remap = false,
                    { "<leader>gt", "<cmd>GpChatNew tabnew<cr>",   desc = "New Chat tabnew" },
                    { "<leader>gv", "<cmd>GpChatNew vsplit<cr>",   desc = "New Chat vsplit" },
                    { "<leader>gx", "<cmd>GpChatNew split<cr>",    desc = "New Chat split" },
                    { "<leader>ga",     "<cmd>GpAppend<cr>",           desc = "Append (after)" },
                    { "<leader>gb",     "<cmd>GpPrepend<cr>",          desc = "Prepend (before)" },
                    { "<leader>gc",     "<cmd>GpChatNew<cr>",          desc = "New Chat" },
                    { "<leader>gf",     "<cmd>GpChatFinder<cr>",       desc = "Chat Finder" },
                    { "<leader>gg",     group = "generate into new .." },
                    { "<leader>gge",    "<cmd>GpEnew<cr>",             desc = "GpEnew" },
                    { "<leader>ggn",    "<cmd>GpNew<cr>",              desc = "GpNew" },
                    { "<leader>ggp",    "<cmd>GpPopup<cr>",            desc = "Popup" },
                    { "<leader>ggt",    "<cmd>GpTabnew<cr>",           desc = "GpTabnew" },
                    { "<leader>ggv",    "<cmd>GpVnew<cr>",             desc = "GpVnew" },
                    { "<leader>gn",     "<cmd>GpNextAgent<cr>",        desc = "Next Agent" },
                    { "<leader>gr",     "<cmd>GpRewrite<cr>",          desc = "Inline Rewrite" },
                    { "<leader>gs",     "<cmd>GpStop<cr>",             desc = "GpStop" },
                    { "<leader>gt",     "<cmd>GpChatToggle<cr>",       desc = "Toggle Chat" },
                    { "<leader>gw",     group = "Whisper" },
                    { "<leader>gwa",    "<cmd>GpWhisperAppend<cr>",    desc = "Whisper Append (after)" },
                    { "<leader>gwb",    "<cmd>GpWhisperPrepend<cr>",   desc = "Whisper Prepend (before)" },
                    { "<leader>gwe",    "<cmd>GpWhisperEnew<cr>",      desc = "Whisper Enew" },
                    { "<leader>gwn",    "<cmd>GpWhisperNew<cr>",       desc = "Whisper New" },
                    { "<leader>gwp",    "<cmd>GpWhisperPopup<cr>",     desc = "Whisper Popup" },
                    { "<leader>gwr",    "<cmd>GpWhisperRewrite<cr>",   desc = "Whisper Inline Rewrite" },
                    { "<leader>gwt",    "<cmd>GpWhisperTabnew<cr>",    desc = "Whisper Tabnew" },
                    { "<leader>gwv",    "<cmd>GpWhisperVnew<cr>",      desc = "Whisper Vnew" },
                    { "<leader>gww",    "<cmd>GpWhisper<cr>",          desc = "Whisper" },
                    { "<leader>gx",     "<cmd>GpContext<cr>",          desc = "Toggle GpContext" },
                },
            })
        end,
    }
}
